args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 2) {
  stop("Usage: predict_patient.R <bundle.json> <request.json>")
}

bundle_path <- normalizePath(args[[1]])
request_path <- normalizePath(args[[2]])

script_file <- normalizePath(sub("^--file=", "", commandArgs(trailingOnly = FALSE)[grepl("^--file=", commandArgs(trailingOnly = FALSE))][1]))
script_dir <- dirname(script_file)
package_root <- normalizePath(file.path(script_dir, "..", ".."))

source(file.path(package_root, "R", "data_prep.R"), local = TRUE)
source(file.path(package_root, "R", "model.R"), local = TRUE)

bundle <- stg_load_model_bundle(bundle_path)
request <- jsonlite::fromJSON(request_path, simplifyVector = TRUE)

if (is.data.frame(request)) {
  new_data <- request
} else if (is.list(request)) {
  new_data <- as.data.frame(request, stringsAsFactors = FALSE, check.names = FALSE)
} else {
  stop("Request must be a JSON object or row-oriented JSON data frame")
}

new_data <- stg_prepare_data(new_data, select_features = TRUE, include_target = FALSE, dedupe = FALSE)

predictions <- stg_predict_portable(bundle, new_data)

cleaned <- stg_prepare_data(new_data, select_features = TRUE, include_target = FALSE, dedupe = FALSE)
feature_means <- unlist(bundle$feature_means, use.names = TRUE)
feature_sds <- unlist(bundle$feature_sds, use.names = TRUE)
coefficients <- unlist(bundle$coefficients, use.names = TRUE)

for (column in bundle$numeric_columns) {
  cleaned[[column]] <- (cleaned[[column]] - feature_means[[column]]) / feature_sds[[column]]
}

feature_alias <- c(
  "Gender" = "Child gender",
  "Age" = "Child age",
  "Birth_Weight" = "Birth weight",
  "Birth_Length" = "Birth length",
  "Body_Weight" = "Current body weight"
)

row_values <- unlist(cleaned[1, c("Gender", "Age", "Birth_Weight", "Birth_Length", "Body_Weight")], use.names = TRUE)
contrib <- coefficients[names(row_values)] * row_values
contrib <- contrib[order(abs(contrib), decreasing = TRUE)]
top_features <- names(contrib)[seq_len(min(3, length(contrib)))]
top_risk_drivers <- unname(feature_alias[top_features])

out <- list(
  probability = as.numeric(predictions$probability[1]),
  predicted_class = as.character(predictions$predicted_class[1]),
  model_type = bundle$model_type,
  selected_features = bundle$selected_features,
  top_risk_drivers = top_risk_drivers,
  message = "Prediction generated by stuntguardr"
)

cat(jsonlite::toJSON(out, auto_unbox = TRUE, pretty = TRUE))
